stages:
  - release

helm-upload-gitlab:
  stage: release
  image: alpine/helm:3.10.2
  services:
    - docker:dind
  variables:
    PKG_CHANNEL: stable
    PKG_NAME: momo-store
    PKG_VERSION: 1.0.0
    CHART_NAME: momo-store
  before_script:
    # Плагин для cm-push
    - helm plugin install https://github.com/chartmuseum/helm-push
  script:
    # Создание helm пакета
    - helm package helm/ --version ${PKG_VERSION}
    # Добавление репозитория
    - helm repo add --username gitlab-ci-token --password $CI_JOB_TOKEN ${CHART_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/${PKG_CHANNEL}
    - echo ${CI_PROJECT_ID}
    - echo ${CI_API_V4_URL}
    # Загрузка в репозиторий
    - helm cm-push ./${PKG_NAME}-${PKG_VERSION}.tgz ${CHART_NAME}
    - helm repo update
  when: manual
  
helm-upload-nexus:
  stage: release
  image: dtzar/helm-kubectl
  script:
    - helm package ./helm --version=$VERSION
    - curl -v -u "${NEXUS_USER}:${NEXUS_PASS}" $NEXUS_HELM_REPO --upload-file ./momo-store-${VERSION}.tgz 
  when: manual
