apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-hpa
  labels:
    app: {{ .Chart.Name }}-hpa
spec:
  minReplicas: {{ .Values.hpaSpec.minReplicas }}
  maxReplicas: {{ .Values.hpaSpec.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: momo-backend-{{ .Release.Name }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpaSpec.cpuUtilization }}
