apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-frontend-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: momo-frontend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: momo-store
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        prometheus.io/port: "{{ .Values.exporterPort }}"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.image}}:{{.Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: {{ .Values.env.name }}
              value: "https://{{ .Values.fqdn }}/api"
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/momo-store.conf
              subPath: momo-store.conf
              readOnly: true
        - name: nginx-exporter
          image: {{ .Values.imagexporter }}
          args:
            - '-nginx.scrape-uri=http://localhost:{{ .Values.service.port }}/nginx_status'
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.exporterPort }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: momo-store.conf
                path: momo-store.conf
      imagePullSecrets:
        - name: docker-config-secret
