apiVersion: v1
kind: Secret
metadata:
  name: gitlab-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.vnaz.site/musasy/momo-store.git
  password: <AccessToken>
  username: <name>